name: Build, push, and deploy

on:
    push:
        branches:
            - main
        paths:
            - "Dockerfile"
            - ".github/workflows/**"

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DOCR_ACCESS_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to DigitalOcean Container Registry
              uses: docker/login-action@v2
              with:
                  registry: registry.digitalocean.com
                  username: ${{ secrets.DOCR_USERNAME }}
                  password: ${{ secrets.DOCR_ACCESS_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: registry.digitalocean.com/${{ secrets.DOCR_REPOSITORY }}/frontend
                  tags: frontend

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: registry.digitalocean.com/${{ secrets.DOCR_REPOSITORY }}/frontend:frontend
                  labels: ${{ steps.meta.outputs.labels }}
